language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.2
    - 7.3
    - nightly

env:
  matrix:
    - COMPOSER_PARAM="update --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress --prefer-lowest"
    - COMPOSER_PARAM="update --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"

matrix:
  allow_failures:
    - php: nightly

before_script:
    - composer selfupdate
    - composer $COMPOSER_PARAM

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
